language: ruby
env:
  global:
  - secure: yeOQtJceFV1fQ1Tbo/8Qp6GQXtH9+u3+9yEg+mtAM4cUwt6U2fKye70GlIRyDaB36DFXbGH10+3ES+/ZeJge3uWsSBL4e6h6Lip/vXd2XWROiGTdU/FzM0sJ2dYlPkHvozFgIsbBPkRwmj1cl0WYO6m0tGbVqScy6yhgfXjqBAw=
branches:
  only:
  - develop
before_install:
- travis_retry gem install jekyll
- bundle install
before_script:
- git config --global user.email "halfdane@gmx.net"
- git config --global user.name "halfdane"
- git clone --quiet --branch=master "https://${GH_TOKEN}@github.com/halfdane/halfdane.github.io" _site
- git rm -rf *.css *.js js css scss
script:
- rake build
after_success:
- cd _site
- git add .
- git commit -m "[ci skip] snapshot $(date '+%m/%d/%y %H:%M')"
- git push "https://${GH_TOKEN}@github.com/halfdane/halfdane.github.io"
- cd ..
