language: ruby
env:
  global:
  - secure: yeOQtJceFV1fQ1Tbo/8Qp6GQXtH9+u3+9yEg+mtAM4cUwt6U2fKye70GlIRyDaB36DFXbGH10+3ES+/ZeJge3uWsSBL4e6h6Lip/vXd2XWROiGTdU/FzM0sJ2dYlPkHvozFgIsbBPkRwmj1cl0WYO6m0tGbVqScy6yhgfXjqBAw=
branches:
  only:
  - develop
before_install:
- git --no-pager log -1 --oneline
- travis_retry gem install jekyll
script:
- jekyll build
after_success:
- ls -la
- la -la ../
- git fetch origin master:master
- git checkout master
- ls | grep -v _site | xargs rm -rf
- mv _site/* .
- mv _site/.* .
- rmdir _site
- git add .
- git config --global user.email "halfdane@gmx.net"
- git config --global user.name "halfdane"
- git status
- git commit -m "[ci skip] snapshot $(date '+%m/%d/%y %H:%M')"
- git push "https://${GH_TOKEN}@github.com/halfdane/halfdane.github.io"
- cd ..
