title: "Canned Nerd"
subtitle: "Navigate By Sight"
name: "halfdane"

description: | 
  Sometimes, I'm a little bit like a squirrel: I'll do whatever catches my fancy.
  At least in my private time.
  This is where I keep what I've done.
url: "https://halfdane.github.io"
repository: "halfdane/halfdane.github.io"
#logo: "/assets/images/88x88.png"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


social:
  links:
    - "https://www.reddit.com/user/half_dane/"
    - "https://beta.nft.gamestop.com/halfdane.eth"
    - "https://www.reddit.com/r/Superstonk/"

author:
  name     : "HalfDane (he/him)"
  avatar   : "/assets/images/halfdane.png"
  bio      : "Software Engineer by trade, reckless tinkerer by passion."
  location : "Germany"
  links:
    - label: "Superstonk"
      url: "https://www.reddit.com/r/Superstonk/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/halfdane"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/half_dane"
    - label: "halfdane.eth"
      icon: "fab fa-fw fa-ethereum"
      url: "https://etherscan.io/address/0xff33d93d62735088abdb8d8489d0e95367266926"
    - label: "Gamestop NFT Marketplace"
      url: "https://beta.nft.gamestop.com/halfdane.eth"



minimal_mistakes_skin: "dark"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

